name: Build and Deploy Backend to AWS

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      SELECTOR_URL: ${{ secrets.SELECTOR_URL }},
      KEY: ${{ secrets.KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - run: |
          cd lambda-node
          npm install --save-dev esbuild  # Install esbuild as a dev dependency
          npm ci                          # Install project dependencies from package-lock.json

      - run: |
          cd lambda-node
          npm run build                    # Runs sam build, copy-prisma, and copy-schema

      - run: |
          cd lambda-node
          echo "=== Directory size breakdown ==="
          du -h -d 1 .
          echo "=== node_modules size breakdown ==="
          du -h -d 1 ./node_modules | sort -hr
          echo "=== Total unzipped size ==="
          du -sh .

      - run: |
          cd lambda-node
          npm prune --production  # Remove dev dependencies (including esbuild) after build

      - run: |
          cd lambda-node
          sam deploy   --stack-name song-thing --region ap-southeast-2    --parameter-overrides SelectorUrl=${{ secrets.SELECTOR_URL }} Key=${{ secrets.Key }}  DatabaseUrl=${{ secrets.DATABASE_URL }} NextAuthSecret=${{ secrets.NEXTAUTH_SECRET }} FrontendUrl=${{secrets.FRONTEND_URL}} --capabilities CAPABILITY_IAM   --resolve-s3   --no-confirm-changeset   --no-fail-on-empty-changeset   --force-upload   --no-progressbar
